### PR TITLE
Fix for 3844-theming-problem-in-preferences

### PR DESCRIPTION
**Pull request by Blenux**
-- adjusted the USERPREF_PT_save_preferences panel to match rest of Bforartists theme. 
-- adjusted the userdef_default_theme.c also value for above too (might be causing it?).

Screenshot_20231005_125656

### CODE REVIEW

**Comment by ReinerBforartists** [comment]
Good job, but please also update the userpref.blend file in tools\utils

That the blend file is not updated shows me that you did edit the files manually. Which we should never do. I'm the same here with the Blender developers. Never edit the userdef_default_theme.c by hand. It needs to be created by the blender_theme_as_c.py script in the tools\utils directory. Else you might miss some entries.

The steps are described in the python scriptitself.

blenderthemeasc

**Comment by Blenux** [comment]
Oh I didn't realize, my bad so do I revert the changes in this pull and only upload the .blend?

**Comment by ReinerBforartists** [comment]
> Oh I didn't realize, my bad so do I revert the changes in this pull and only upload the .blend?

No, redo the whole procedure by doing it by script. As seen in the discord, we have new content from Blender. And this new content needs to arrive in our theming somehow. What you need to do is to follow all the steps, including regenerating the bforartists.xml file then from the preferences. As shown here:

https://github.com/Bforartists/Bforartists/wiki/Changing-the-Default-Theme

**Comment by ReinerBforartists** [comment]
Looking at the changes, this looks good now. I'll merge it in, and make a new task for the other themes.

**Comment by ReinerBforartists** [comment]
Related: https://github.com/Bforartists/Bforartists/issues/3834

**Pull request merged**
