### PR TITLE
Compilation warning - missing format arguments for BLI_sprintfN #2064

### LINKED ISSUE #2064: Compilation warning - missing format arguments for BLI_sprintfN
image

### PR DESCRIPTION
**Pull request by iyadahmed**
Fixes #2064 
image

### CODE REVIEW

**Comment by ReinerBforartists** [comment]
I will download the branch and make a few tests first. I still fear that you break the functionality with your change back. There are some very special tooltip titles that doesn't show when you check for but_label.strinfo.

The culprit here is this check, wich i have disabled for good reason: if (but_label.strinfo && !STRPREFIX(but->drawstr, but_label.strinfo)) {

**Comment by iyadahmed** [comment]
> I will download the branch and make a few tests first. I still fear that you break the functionality with your change back. There are some very special tooltip titles that doesn't show when you check for but_label.strinfo.
> 
> The culprit here is this check, wich i have disabled for good reason: if (but_label.strinfo && !STRPREFIX(but->drawstr, but_label.strinfo)) {

alright, will also try to solve the warning without killing the feature now

**Comment by iyadahmed** [comment]
I think simply using %s without . in the first condition will solve the warning, without changing what the code does

**Comment by ReinerBforartists** [comment]
Great. And sorry for the misunderstandings. I am not this good at working at several things at once :)

The mean part is that the tooltips and the titles are implemented in the usual Blender manner. Everything in its own way. Plus the design decision not to show the tool name in the title everywhere. I have never understood the reason why they let the user guess what tool or menu it is.

**Comment by iyadahmed** [comment]
Indeed, I think it is sorted out now, also we can just remove the first condition, but will use an empty string as format string, because using %s makes an empty space at the top of the tooltip, but let's test first, which tooltips are affected by this?

**Comment by ReinerBforartists** [comment]
> I think simply using "%s" without . in the first condition will solve the warning, without changing what the code does

Isn't that the dot at the end? Ah, my C fu is simply too weak ^^

**Comment by iyadahmed** [comment]
> > I think simply using "%s" without . in the first condition will solve the warning, without changing what the code does
> 
> Isn't that the dot at the end? Ah, my C fu is simply too weak ^^

ah yep we remove the dot, that what cause the visual issue, but if we leave the %s it simply displays an empty string (value but_label.strinfo), which takes space at the top of the tooltip

**Comment by iyadahmed** [comment]
I think this would fix, but not sure if it affects the specific tooltips, need to test
image

**Comment by ReinerBforartists** [comment]
> Indeed I complicated things ^^, I'm sorry I made multiple changes, it is not good that way,
> I think it is sorted out now, also we can just remove the first condition, but will use an empty string as format string, because using %s makes an empty space at the top of the tooltip, but let's test first, which tooltips are affected by this?

It is more than a dozen from what i remember. I would have to collect them again too. The range goes across simple operators across menu names , property names and so on. Some works as thought, some not. I don't find the original issue at the moment. My poor hands ... :(

But affected are for example the buttons to create the primitives in our toolbar at the top.

You could add a test string and go through the UI to see what is affected and what not.

**Comment by iyadahmed** [comment]
> > Indeed I complicated things ^^, I'm sorry I made multiple changes, it is not good that way,
> > I think it is sorted out now, also we can just remove the first condition, but will use an empty string as format string, because using %s makes an empty space at the top of the tooltip, but let's test first, which tooltips are affected by this?
> 
> No harm done. That's development ^^
> 
> It is more than a dozen from what i remember. I would have to collect them again too. The range goes across simple operators across menu names , property names and so on. Some works as thought, some not. I don't find the original issue at the moment. My poor hands ... :(
> 
> But affected are for example the buttons to create the primitives in our toolbar at the top.
> 
> You could add a test string and go through the UI to see what is affected and what not.

right ^^, ok great will test now

**Comment by iyadahmed** [comment]
it crashes if we remove it entirely, so trying the other way

**Comment by ReinerBforartists** [comment]
Ah you already found the original issue it seems. https://github.com/Bforartists/Bforartists/issues/1293

But i haven't listed all affected elements here. The problem of this task was that the tabs in the properties editor did show a dot above the tooltip. And here one line is enough. No title required.

**Comment by iyadahmed** [comment]
will upload the branch again, I was concerned about an empty space at the top of some tooltips, but i turned out it was there already, the change would be to use "%s" in the first condition too, no difference after change, but removed the warning

**Comment by ReinerBforartists** [comment]
When we have unexpected spaces in the tooltip titles then this would be another task. Do you have an example? :)

**Comment by iyadahmed** [comment]
sure the tooltips that had a dot before, now has an empty space
image

**Comment by ReinerBforartists** [comment]
Ah, i see. Never found a solution for that. You can make a task for it if you want.

**Comment by iyadahmed** [comment]
great making a task now

**Pull request closed without merging**
