### PR TITLE
Fix 3423 issue

### PR DESCRIPTION
**Pull request by Blenux**
Added extra keymap to fix the 3d view 3dcursor not draggable issue.

### CODE REVIEW

**Comment by ReinerBforartists** [comment]
Don't forget the Mac keymap. It needs the same fix :)

**Comment by Blenux** [comment]
oops, done.

**Comment by Draise14** [comment]
WIll merge in after the Blender merge for this week.

**Comment by iyadahmed** [comment]
I would have merged it, we didn't confirm on a mac though but I suppose it works

**Comment by ReinerBforartists** [comment]
I had an eye at it. And despite not having a mac, it looks ok :)

Worries with the mac version is always that you accidentally change the oskey back to ctrl ...

**Pull request merged**
