### PR TITLE
3D View - Hotkey only Operator - Transform Axis Target on lights has …

### PR DESCRIPTION
**Pull request by iyadahmed**
…no UI entry #1892
image

### CODE REVIEW

**Comment by ReinerBforartists** [comment]
As told in the issue, we should add the operator to the object menu too. And update the tooltip.

**Comment by iyadahmed** [comment]
> As told in the issue, we should add the operator to the object menu too. And update the tooltip.

oh ok will do now

**Comment by iyadahmed** [comment]
while looking at operator source, edited tool tip, and found a nicer name for the menu entry
image

**Comment by iyadahmed** [comment]
restored original tool-tip, renamed menu entry
image

**Comment by ReinerBforartists** [comment]
Great so far. Remains to remove the hint to the camera and to add the hint for the useage of the tool.

**Comment by iyadahmed** [comment]
adding now

**Comment by ReinerBforartists** [comment]
Don't forget to rename the entry in the object menu too.

**Comment by iyadahmed** [comment]
> Don't forget to rename the entry in the object menu too.

already did :)

**Comment by iyadahmed** [comment]
wrote this usage hint, how does it read to you?
image

**Comment by ReinerBforartists** [comment]
We're getting close! But it is not clear with your tooltip that you first need to select the target object, then shift select the light , and then you can perform the tool. The object and shift select part is missing. Please change it to the following:

Select object, shift select light so that both are selected, perform tool

**Comment by iyadahmed** [comment]
ok, will do now, the reason is I couldn't make it work by selecting target, it seems to make no difference if target is not selected, I might be missing something, changing now.

**Comment by ReinerBforartists** [comment]
When you use it without an object selected then the light just rotates around in screen space. With a target object selected it will point in direction of the object in screen space, and will point through this object.

It's an awkward tool,  no question ^^

**Comment by iyadahmed** [comment]
> When you use it without an object selected then the light just rotates around in screen space. With a target object selected it will point in direction of the object in screen space, and will point through this object.
> 
> It's an awkward tool, no question ^^

oh I see, indeed ^^

**Comment by ReinerBforartists** [comment]
Yeah, it's hard to see. When you use two views then it is better noticeable. Took me also a while to figure it out back in the days when i first found out about this tool ^^

**Comment by iyadahmed** [comment]
> Yeah, it's hard to see. When you use two views then it is better noticeable. Took me also a while to figure it out back in the days when i first found out about this tool ^^

oh makes sense ^^

**Comment by iyadahmed** [comment]
Updated message
      "Interactively point lights to a location (Ctrl translates and aligns to target normal)\n"
      "(optionally select a target Object and a Light, then use this operator)"

added "optionally" because it can be used without, if not suitable can be changed

**Comment by ReinerBforartists** [comment]
> wrote this usage hint, how does it read to you?
> image

It is still wrong XD
And while at it, it also misses the hint towards hotkey tool.

Interactively point a light towards an object (Ctrl translates and aligns to target normal)
Select object and shift select light. Perform tool and point to target
Hotkey tool! Please use the hotkey!

I would suggest to use exact this text so that we can finally close this pull request :)

**Comment by iyadahmed** [comment]
> > wrote this usage hint, how does it read to you?
> > image
> 
> It is still wrong XD
> And while at it, it also misses the hint towards hotkey tool.
> 
> Interactively point a light towards an object (Ctrl translates and aligns to target normal)
> Select object and shift select light. Perform tool and point to target
> Without target object the light rotates freely
> Hotkey tool! Please use the hotkey!
> 
> I would suggest to use exact this text so that we can finally close this pull request :)
> 
> Note to myself. Yet another proof why it is better to split the tasks into as small steps as possible. And not to extend a task more and more. We should have split this up into its parts. Next time ...

ok will do now, I arrived home late yesterday, just woke up now

**Comment by iyadahmed** [comment]
Done
image

**Comment by ReinerBforartists** [comment]
Aaand closed :)

**Pull request merged**
