### PR TITLE
Animation - Apply Animation to all selected through UI Animate proper…

### LINKED ISSUE #2163: Animation - Apply Animation to all selected through UI Animate property buttons
# Issue
bforartists_i2dNYBJh37

Currently, when you animate with characters or multiple objects, you can key all of them by pressing I then selecting which properties you want to animate from a very long un-iconized list. 

Like in Bforartsits as in Blender, if you use the UI entries, you can only set animation on Active object properties.
bforartists_vb1Zrgy5dx

In general, the UX for all selected is holding down ALT then editing the sliders and it would apply to all selected. 

# Feature Request
It would improve the UX if we could animate all selected by holding down ALT then pressing the keyframe UI entry, then it would add and set keyframes for all selected, just like the "I" then Keyframe Panel operators. 

This may be... a global change, but here the focus is to focus on the animation properties of the Transform Panel

# Task
image

- Research to see if this is possible, to be able to use the UI entry to then trigger animation key to all selected
- Evaluate how this can be implemented
- Evaluate if this is a feature that should be committed to Blender directly, or set here

## Method
I've asked @iyadahmed to do some research into this, document it and find away to save some time figuring it out to give us some options.

### PR DESCRIPTION
**Pull request by iyadahmed**
Fixes #2163 
…ty buttons #2163

### CODE REVIEW

**Comment by Draise14** [comment]
Just tested this out, the apply animation to bones is currently not fully working, so this needs more work before being pulled. So.. needs a bit more work.

**Comment by iyadahmed** [comment]
Yep It is currently a draft

**Comment by ReinerBforartists** [comment]
And drafts cannot be merged. So please be patient ;)

I have a permanent eye at the pull requests. But currently i have not this much to add to the two drafts. @iyadahmed you can always poke me in case i overlook something.

**Comment by iyadahmed** [comment]
Alright :)

**Comment by ReinerBforartists** [comment]
Hey Iyad,

Shall we finally close this request until you are ready to commit? The master evolves permanently ... :)

**Comment by iyadahmed** [comment]
> Hey Iyad,
> 
> 
> 
> Shall we finally close this request until you are ready to commit? The master evolves permanently ... :)

Sure :), we can close for now, until the patch becomes ready

**Pull request closed without merging**
