### PR TITLE
fix for 3891-geometry-nodes-sidebar-group-tab-interface-panel-same-to…

### PR DESCRIPTION
**Pull request by Blenux**
--- Separated add operators with own descriptions.

add_input
add_panel
add_output

### CODE REVIEW

**Comment by ReinerBforartists** [comment]
I know that we usually don't comment changes in the python files. But this mainly affects the files in startup/bl_ui. But you modified a python file in startup/bl_operators here. And there is a high danger that your change will be reverted with a merge then.

May i ask you for the favour to comment your changes in the node.py file? :)

**Comment by Blenux** [comment]
Ok can do.

**Comment by Blenux** [comment]
hows that?

**Comment by iyadahmed** [comment]
Btw what do you mean poll not needed?

**Comment by ReinerBforartists** [comment]
No idea, sorry, these commments are not from me. I think @iyadahmed Did these comments.

Mh, i meant this lines here. Every change from us should have a comment here.

thischanges

**Comment by iyadahmed** [comment]
No worries all good ^^

**Comment by Blenux** [comment]
ah right I will recheck and see if I can fix soon (totally forgot why I did it this way lol)

**Comment by Blenux** [comment]
should be good now (fingers cross :smile: )

**Pull request merged**
