### PR TITLE
Initial add exposed asset shelves for 3d viewport and node editor

### PR DESCRIPTION
**Pull request by zNightlord**
Add asset shelf for objects, materials, collections for the 3d viewport, node group asset for node editors (Geometry, Shader, Compositor)
For 3D viewport the default drag behavior would be using instances. 
 `asset_drag->drop_collections_as_instances = true;`
 I can't figure out a proper way to really hook up the buttons, props I made under `AssetShelfSettings` and put in `AssetDragController::create_drag_data`
 
 As for node editors for the default assets, editor filtering I think it's better to define asset [tags ](https://docs.blender.org/api/current/bpy.types.AssetMetaData.html#bpy.types.AssetMetaData.tags) replacement for the current `not asset.name.startswith("S_")` and also for user made node group have to set it up like that for have it properly place in the right node editor type.
 ```py
    @classmethod
    def asset_poll(cls, asset):
        return asset.id_type == 'NODETREE' and not asset.name.startswith("S_")
 ```

image
*ignore the drop instance buttons* 

Extra TODOs for this:
- [ ] Make startup file properly adapt to this
- [x] Adjust versioning code part
- [x]  Typos.

### CODE REVIEW

**Comment by Draise14** [comment]
This is a big awesome feature set! 

Maybe for the 3D View, the collection center to world origin and as collection should follow the asset browser settings instead of override?

**Comment by zNightlord** [comment]
> This is a big awesome feature set!
> 
> Maybe for the 3D View, the collection center to world origin and as collection should follow the asset browser settings instead of override?

The asset browser is in a different context space data unfortunately, unless you move it to the Bforartists preferences addon or under preferences.
Related #3562

**Comment by Draise14** [comment]
The properties toggles were set in C, then exposed to the header. But yeah.. might need some thought. I will use the new tag system to filter, so a user can use a tag instead of name. It will clean up the prefix names, not so user friendly anyway.

**Comment by Draise14** [comment]
Work is nearly done, will be able to review it early next week.

**Comment by Draise14** [comment]
Ok, going to pull your branch and do a review. If it seems to work and we have a "default" action for the asset shelf, we can later find new operators to drag things in with the user opt-in (link, append, reuse, etc - then collection or world origin for the 3D View) but that can be new tasks.

**Comment by Draise14** [comment]
Compiled. It works and follows the file Browser settings of linking or appending.

I did find a blender bug though when linking collection to scene, not as instance.

**Comment by zNightlord** [comment]
It's the same operator call as the asset browser one. That actually gives me one idea on how to do something with the button problem for later.

> I did find a blender bug though when linking collection to scene, not as instance.
Hmm, I can't replicate that bug.

**Comment by Draise14** [comment]
Ok, blender fixed the bug, but that would come in the next release. They may have also removed a redundet property we built to compensate the broken UX (dragging in a collection not as instance would offset linked data). 

https://projects.blender.org/blender/blender/issues/126568

**Pull request merged**
