### PR TITLE
 Video Sequencer - re-organize the Change Effect Type menu's to be consistent with Add menus #894 

### PR DESCRIPTION
**Pull request by Draise14**
Video Sequencer - re-organize the Change Effect Type menu's to be consistent with Add menus #894 

- Added separators to enumerated menu to be a little more consistent without changing features
- Added icons to enumerated menu
- fixed icons to match in enumerated menu for consistency

### CODE REVIEW

**Comment by Draise14** [comment]
Weird, task #843 that I re-opened and recommitted after a merge regression got lumped into this pull request automatically.

**Comment by ReinerBforartists** [comment]
That's normal. There must be a way to commit changes to the pull request ...

Ideally please just make one pull request for one task. But sometimes it's not to avoid to have more than one task in a pull request. The problem is, it makes me more work to check then ...

I promise to merge it as fast as possible, so that you can continue :)

**Comment by ReinerBforartists** [comment]
The second reason why just one commit for one issue is, when you need something to correct then you end in a big mess.

Found a small thing already that needs correction. You usually add two paragraphs between two classes. You made a big gap here in line 3916 and 3917. This should be avoided for readability.

https://github.com/Bforartists/Bforartists/pull/902/commits/58387124febc286e51aeeff33a41fcb176d8380c#diff-6382b06ba650d03ff16d0df4b906873e

**Comment by Draise14** [comment]
Alright, so.. only do one task then pull for one each sitting or so. I removed the empty the spaces you mentioned and recommitted.

**Comment by ReinerBforartists** [comment]
Thanks :)

Ah, i see you added new lines to the menus in the c files. Could you please next time add a comment there? A hint that this change comes from us? Something like:

/*bfa - modified menu, added spaces*/

Background is, changes in c can easily get lost with merges. I don't have all changes in my head. And maybe we stumble across it in a year or two again. When it's an icon or a tooltip, then the change is obvious. But such new lines are not so obvious.

**Comment by ReinerBforartists** [comment]
Merged

**Pull request merged**
