### PR TITLE
fix add light group state!

### PR DESCRIPTION
**Pull request by cl3m3c7**
by default the add group button is greyed out!
this commit fixes it!

### CODE REVIEW

**Comment by Draise14** [comment]
Hey there! First commit! Welcome. And thanks for the quick patch. I'll review and compare with Blender here. 

Just to let you know, we do have a little standard to keep gitflow clean and easy to track - when you make a branch, make sure there is a task issue open for that branch with the same #0000 listed from the task. And when you commit to that branch to pull, make sure the commit also has the same number, then we when we track code and also release logs, it will be a lot easier. 

I have had a quick look and compared with the devbuild, I do not see the issue and and cannot reproduce. I am doing an official build with cycles now to test with todays master. 
image

**Comment by cl3m3c7** [comment]
not this one but add light group located in both world -> settings and object options -> shading

**Comment by Draise14** [comment]
@cl3m3c7 I am seeing you commit to this branch without tracking tasks. It would be nice to meet you in person in the discord community. Also, here is a welcome package. I can't accept any pull requests till we know what you're exactly trying to fix or propose. 

Feel free to apply as a dev here in Discord or drop a new discussion here in the tracker forums:

**Discord**
https://discord.gg/yKuR77v

If anything, here is an intro:

# **Developer Welcome Package:**
As a developer for Bforartists, you have access to commit to Github, start discussions, commit code, do and learn more. 

There are three github repositories
1. Bforaritsts - the source code and tracker https://github.com/Bforartists/Bforartists
2. Manual - the documentation and reference manual https://github.com/Bforartists/files
3. Files - the publicity assets, icon files and press kit material https://github.com/Bforartists/Manual

We also have developer documentation to build bforartists, how to make icons, and the pull request tutorial to work in the tracker. 
This tutorial is important, how to work in the tracker: https://www.bforartists.de/data/tuts/pullrequest_tutorial.pdf

General workflow it based on Gitflow:

## Preliminary workflow:
1. If you want a feature request, create a task and assign the "Feature Request" tag. (or start a discussion in the discussion tracker)
2. When the task or discussion is accepted by one of the core devs (Iyad, Draise or Reiner) as a task, it will become a "Task" to do. 
3. Once it's a task, this can then be used as a basis for branching, committing and doing a pull request. 

- Tasks should contain an image (always) of a mockup or the problem in the GUI. Images speak thousands of words, so best start there. 
- Should contain a title starting with the editor, the mode, then the feature to fix. (eg. 3D View - Edit Mode - Make and assign icon for new operator)
- Should contain a description of the problem
- Should contain a solution or plan of action to resolve the problem.
 
 
## Commit Gitflow:
When you are ready to do code, these are the general guidlines we follow:
1. Assign yourself to a created task
2. Create a branch from master with the #number of the task (eg.#3008 with description "Icon Sheet - A lost Icon has no name" )
3. Switch to branch
4. Do code
5. Compile to make sure nothing is broken (lite version is fine since this is mostly GUI)
6. Commit  with the #number of the task (eg.#3008 with description "Icon Sheet - A lost Icon has no name, added icon" )
7. Create a pull request
8. Fix anything that would conflict (if any). 
9. Update any documentation (or create a task for documentation update with screen capture of update in the Manual repository tracker)
10. Close task after commit and label "Fixed"

When the pull is clean, then we merge to master, and you can repeat process. It is usually good practice to branch any new task, and pull any new task - and to focus on one task at a time for clean and efficient code management with others. It is also important every task gets documentation. Thanks for the attention to detail!

**Comment by Draise14** [comment]
Had a look in the blender master, looks like this is greyed out intentionally, thus it would be a change for Blender to do. Though I will test the patch to see if it improves the UX. But for now we probably should make an actual issue to track this change first and then create another issue and branch for your second theme commit. 

image

**Comment by cl3m3c7** [comment]
ok sorry for the mess :)

**Comment by Draise14** [comment]
The reports you must have done must have been with Blender, we don't usually have priority, it's either a **feature request**, a **task**, or **postponed**. 

You can always start your requests in the tracker with Bforaritsts with a label "Feature Request" and it will be discussed openly. I have already made your light groups button task a task to track now. 

https://github.com/Bforartists/Bforartists/issues/3096

If you can kindly make a new issue for your theme changes, with some screen captures and reason why the changes, then we can review that one also in another branch. I will close this pull request, and we can start again with the individual branches and tasks and single pull request per task and commit. So we can be clean. Thank you for the patience! And for the enthusiasm to work here!

**Pull request closed without merging**
