### PR TITLE
Compilation warning - missing format arguments for BLI_sprintfN #2064

### LINKED ISSUE #2064: Compilation warning - missing format arguments for BLI_sprintfN
image

### PR DESCRIPTION
**Pull request by iyadahmed**
Fixes #2064  #2065

### CODE REVIEW

**Comment by ReinerBforartists** [comment]
Ah, now i know what your mentioned warning was about. I did this change to have a tooltip title everywhere. When you change it then we have again tooltips that does not have a tool name.

So before i merge this, can you guarantee that the tooltip titles remains?

And could you please make one pull request per issue? The second is related, yes, but it is a separated issue.

**Comment by ReinerBforartists** [comment]
I will close this pull request. Please one pull request per issue.

**Comment by iyadahmed** [comment]
will split them now

**Comment by ReinerBforartists** [comment]
Thanks :)

**Pull request closed without merging**
