### PR TITLE
fix 4102-ui-clean-up-purge-has-redundant-confirmation-dialogue

### PR DESCRIPTION
**Pull request by Blenux**
-- removed the outliner_orphans_purge_invoke operator, and it's related ops.

### CODE REVIEW

**Comment by Draise14** [comment]
Looks good. I would comment out the code and comment it instead of removing it completely, to make merge work a bit easier.

**Comment by Blenux** [comment]
ah fixed.

**Review by iyadahmed — CHANGES_REQUESTED** [review]
Too much commented code even if removed instead of commented it would be too much removed code, I would vote for reducing the amount of changes to the minimum

**Comment by ReinerBforartists** [comment]
> Too much commented code even if removed instead of commented it would be too much removed code, I would vote for reducing the amount of changes to the minimum

I think this looks fine in general. A bit confusing because of the C++ way to comment out every line with a double slash. The C++ way to use the backslash with stars is of course more elegant. And i think this is what Iyad means. I seem to rememeber that  the blender devs also explicitely asks for the C way to comment, and to avoid the C++ way.

C++ way:

```
//outcommented content 
//outcommented content 
//outcommented content 
```

C way:
```
\* 
outcommented content 
outcommented content 
outcommented content 
*\
```

**Comment by Blenux** [comment]
I'll try to fix this today, once I get back home.

**Comment by Blenux** [comment]
Anyone else wanna tackle this one, can't work out how to comment it out cleanly (without having used function errors during compiling) .

**Comment by ReinerBforartists** [comment]
Hm, we have already a merge conflict here. New libs and stuff is also in the way. Would most probably be easier to start over i guess.

**Comment by ReinerBforartists** [comment]
Excellent. Remains the merge conflict :)

**Pull request merged**
