### PR TITLE
UV Editor - Options - Pixel Snap Mode improvements #1905

### LINKED ISSUE #1905: UV Editor - Options - Pixel Snap Mode improvements
The current implementation is a bit too noisy for my flavour. Neither the icons nor the text is really good to read.

I see two options here. Either we use pure icon buttons. Or we use pure text buttons.

What speaks for the pure icon buttons is that we could make it to a one liner, which reduces visual noise. What speaks for the text buttons is that you don't need to hover over the button to read the tooltip ...

And i don't like the term pixel snap mode. A snap to pixels is much clearer imho.

Suggestions? Ideas?

pixelsnapmode

### PR DESCRIPTION
**Pull request by iyadahmed**
Fixes #1905 
image

### CODE REVIEW

**Comment by iyadahmed** [comment]
will resolve conflict because of the previous commit "hide snap to pixels in image editor"

**Comment by ReinerBforartists** [comment]
It's a trap!

**Comment by iyadahmed** [comment]
oh

**Comment by iyadahmed** [comment]
I deleted the if statement for check if space data mode is UV
maybe that's the reason
adding it back

**Comment by iyadahmed** [comment]
will also do a pull rebase from master

**Comment by iyadahmed** [comment]
I just resolved the conflict on my branch, all is fine :)

**Pull request closed without merging**
