### PR TITLE
3D View - Transform panel change 4L button icon #1937

### LINKED ISSUE #1937: 3D View - Transform panel change 4L button icon
the button looks same, pressed or not
either change icon, or enable emboss
image

### PR DESCRIPTION
**Pull request by iyadahmed**
Fixes #1937 
image

### CODE REVIEW

**Comment by ReinerBforartists** [comment]
Looks good and i will accept it once i am through with the merge of Blender into the master. Sunday is merge day ...

**Comment by iyadahmed** [comment]
Great, saw some nice commits in Blender master recently

**Comment by ReinerBforartists** [comment]
Yeah, and i have a trouble merge again at the moment. Takes a bit longer this time ... ^^

**Comment by iyadahmed** [comment]
Oh, hope it goes well

**Comment by ReinerBforartists** [comment]
We will manage it. It's compiling again. But it's always unfunny when a merge ends in a broken build ^^

**Comment by iyadahmed** [comment]
Great,
Yeah ^^

**Pull request merged**
