### PR TITLE
(2 tasks)  #765 and #843

### PR DESCRIPTION
**Pull request by Draise14**
Video Sequencer - Strip menu needs icons #765
Video Sequencer - Strip menu - Swap enumerated operators menu move up one #843

### CODE REVIEW

**Comment by Draise14** [comment]
The image files have the new icons from #846, but the UI_icons.h file doesn't have them listed, so the DAT files for those icons have not been generated. 

inkscape_2019-05-03_11-30-41

**Comment by ReinerBforartists** [comment]
So what is the actual change here? Is this this monster task?

Keep your hands away from the icons outside of the sheet. Those are icons that are not longer needed. But could still be good place holders. 

We will clean them up once we do the new icon sheet. For now simply ignore them.

**Comment by Draise14** [comment]
This isn't that big, just icons for the tasks I did. #846 looks like it isn't merged in yet... I'll do that now.

**Comment by ReinerBforartists** [comment]
NOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO

One commit one pull request we said :)

**Comment by Draise14** [comment]
Ok... I'll let you do the merge later (I'll make a task). Just to say.. it might have been best to have paused any icon work till I committed and closed the icon work I was doing. 

I'll drop these for now, I have done my work on these tasks, the #846 icon work is still not part of this branch.

**Comment by ReinerBforartists** [comment]
As told in the forum, i will not merge this before the new version is out. I'll do this without pressure. So please be patient a bit.

**Comment by ReinerBforartists** [comment]
Can't accept this pull request, sorry. It breaks everything.

The iconsheet is killed. No icons in the svg file anymore. But odd descriptions that should not be in the sheet. The size fits, but my inkscape version shows nothing. Just curious, what inkscape version are you using? I have still version 0.9.2 here. Either you have an older version than that, or a newer one.

And it seems that the creation itself went also partially wrong. The png files misses the new icons, which should be up right as i can see from your shot and the code. There is none. Which means you did something wrong at one point. Those png files are intermediate steps. Which must contain the new icons.

And last but not least, with your code i can't access the video layout anymore. It closes with a visual basic runtime error. So you broke the code somewhere too :/

noiconsanymore

wherearetheicons

debugproblem

**Comment by Draise14** [comment]
I used Inkscape 0.92.4, the latest stable version on their website. I'll redo this to get it right.

**Comment by ReinerBforartists** [comment]
0.9.2.4 here too. So it's not the inkscape version.

Start with one small task if possible. We first need to nail down what goes wrong here.

**Comment by ReinerBforartists** [comment]
The icon sheet is still empty, all icons gone ...

**Comment by Draise14** [comment]
I merged the master and did a "conflict resolve" to make it revert to the master. The work is being repeated right now. I'll commit again with it compiling correctly later today.

**Comment by ReinerBforartists** [comment]
Looking good now :)

One little thing, please don't use overlong names. This one is a bit too long for my flavour: SEQUENCER_RELOAD STRIPS AND ADJUST LENGTH . Yes i know, that's the tool name. But i would've most probably shortened it to SEQ_RELOAD_AND_ADJUST

We could run into a internal number of characters limit when this icon needs to be used in the C code.

Another thing is that i noticed that you use "inkscape label" . Nothing wrong with that. That's what the inkscape label is meant for. 

I personally simply change the id to the name. Makes the entry shorter, and the list better to read in the xml editor. And you will quickly notice when you have a double in the sheet. Since there can just be one unique id ... . A same label though can exist multiple times.

And you use the name in both in two cases, id and label. One could be cleaned up :)

Sorry for being pedantic here. It most probably works also this way. But would you be so kind to correct the above points. Now is the time to correct such little things. Before it's in the master :)

**Comment by ReinerBforartists** [comment]
We have still a problem with a not accessible video editor layout ...

idandlabel

**Comment by ReinerBforartists** [comment]
I am lost here with this runtime problem. No obvious cause to find. The code is nearly identical. It could have to do with the too long icon names. There could be a limit that we run into here.

I would say shorten the icon names down to let's say maximum 16 characters. Then let's have a second look at the runtime error.

**Comment by Draise14** [comment]
Ok, reproduced the error. Even found the file that has the issue ("stripe_offs" is not initialized). I did only find this in **Debug** building mode though. 

A Release compilation doesn't give me the error. 

bforartists_2019-05-08_09-22-40

**Comment by ReinerBforartists** [comment]
Is the error gone now after shorten the icon names? As told, i am as clueless as you. The code looks correct. The only real difference that counts is the icon names.

When it still exists, then you might need to go from scratch, with just one icon. And see at which point the error reappears.

**Comment by ReinerBforartists** [comment]
Thanks for the hint with the debug build Draise. This error appears in the master too. Funny little rascal.

Okay, i will check your branch again, and merge it when everything looks okay. I will try to catch this error with a debug build error run. It's definitely another issue.

Hmm, how to make a debug build and run debug then would be of interest for you too. The mean part is, it's not necessarily the file in the error report that is the real trouble maker ...

**Comment by ReinerBforartists** [comment]
Created a task for the crash

https://github.com/Bforartists/Bforartists/issues/864

**Comment by ReinerBforartists** [comment]
Found one last thing. You should remove the lines 515 and 516 in the space_sequencer.py file. These lines are obsolete. And there is no reason to keep this code in the python part. When we keep every change here then we end in a mess. In case you want to follow a change then use the git history.

Different story in the C part. Here comments are vital so that the merges doesn't kill old changes. I don't have all vital changes in the head. But icon changes and changes at the tooltips should also here be save even without any comment.

As a side comment, i would put this enum into the top level anyways. Three hierarchies deep is one hierarchy too deep for my flavour. And there is enough space.

And i have to repeat my wish with the icon labeling in the blender_icons.svg. Please use the name in the id part, and remove the inkscape.label from your icons.

You don't need to recreate the icons then. The names are just relevant in the inkscape file, for easier navigation. I don't want to have our sheet as messy as the Blender iconsheet.

remove

delete

**Comment by Draise14** [comment]
> As a side comment, i would put this enum into the top level anyways. Three hierarchies deep is one hierarchy too deep for my flavour. And there is enough space.

Task #843 is to do exactly that. I can commit those changes, sure. 

> And i have to repeat my wish with the icon labeling in the blender_icons.svg. Please use the name in the id part, and remove the inkscape.label from your icons.

>You don't need to recreate the icons then. The names are just relevant in the inkscape file, for easier navigation. I don't want to have our sheet as messy as the Blender iconsheet.

Wait.. but all of them have labels also, and even misnamed ones. 
The ID's currenlty have all the correct names the names, and the Label is the same, as generally the practice I noticed in the file has label as the name (but with a hashtag). 

inkscape_2019-05-08_11-50-58
inkscape_2019-05-08_11-51-08

Is it by putting in the Hashtag that it doesn't show up in the XML? Due to never touching XML in SVG files, I assumed the layer/object in the manager would show it's label (they don't show the ID automatically).

**Comment by Draise14** [comment]
Ok, fixed it up and recommitted the cleaned up iconsheet, no labels now, AND I moved the enumerated swap strips up a level and cleaned that up.

**Comment by ReinerBforartists** [comment]
Yes i know, there is old crap in there. Most of them old Blender icons. But even i made some mistakes in the past. You never stop learning :)

**Comment by ReinerBforartists** [comment]
Done. Files are in master now. Many thanks for your patience :)

**Pull request merged**
