### PR TITLE
Transparent background for the toolshelf tools #2398

### LINKED ISSUE #2398: Transparent background for the toolshelf tools
Not sure if manageable independently. But at the moment it looks odd with the grey background. Maybe we can make just the tools panel background transparent, but keep the background of the other panels intact.

tools

### PR DESCRIPTION
**Pull request by iyadahmed**
Fixes #2398 
This adds a new possible value to bl_options, "HIDE_BG", it sets alpha for panel background to 0
This PR also replaces HIDE_HEADER with HIDE_BG for toolsystem panels
image

### CODE REVIEW

**Comment by ReinerBforartists** [comment]
Sexy :)

Mh, i would love to keep the original tools with the HIDE_HEADER opion on, not with the new option to hide just the background. That way the old and new tools are easier to distinguish. The panels with header are the old tools then. And sorting is still possible. You simply sort the old tools around the new ones. And when you turn off the tabs then you have the exact look like in Blender. No header, transparent background.

**Comment by iyadahmed** [comment]
> Sexy :)
> 
> 
> 
> Mh, i would love to keep the original tools with the HIDE_HEADER opion on, not with the new option to hide just the background. That way the old and new tools are easier to distinguish. The panels with header are the old tools then. And sorting is still possible. You simply sort the old tools around the new ones. And when you turn off the tabs then you have the exact look like in Blender. No header, transparent background.
> 
> 
> 
> EDIT, oh and could you please add our bfa comment to every change in the C code? As told, the danger is that i kill the change with a merge then when there is no proper comment that tells me it is our code.

Many thanks 🙏
Sure will edit it now

**Comment by iyadahmed** [comment]
Hmm, but if we revert to HIDE_HEADER, then the new option is useless, not sure

**Comment by ReinerBforartists** [comment]
As told, the new tool system should stay the old way. The hidden background is just meant for the old toolsystem.

**Comment by iyadahmed** [comment]
Ah I see now, ok changing

**Comment by Draise14** [comment]
> 
> 
> As told, the new tool system should stay the old way, with HIDE_HEADER. The hidden background is just meant for the old toolsystem, our new tabs, where we use HIDE_BG then, to hide the background, but keep the header visible.
> 
> We can always change the new toolsystem to show the toolbar there too. But my belly tells me that it is better to hide the header for this toolset. It doesn't only show in the 3d view ...

I would prefer the new tool system with a header, not only for consistency but it is easier to pin that shelf for all the tabs instead of all the panels from all the tabs to the toolshelf tab with the only group that can't be pinned. The pinning and re-ordering should go both ways for the shortest route possible, new and old.

**Comment by ReinerBforartists** [comment]
And i would prefer not to have a header here:

notgood

And with tooltabs off:

off

As told, we can discuss this at a later point. It does not need to be solved now, in this task. This task here is just to enable the option at all.

**Comment by iyadahmed** [comment]
Changes done ✅ 
As for the discussion, it is annoying to have header hidden,
I also agree that it should like Blender, but, maybe we could make it like that when tabs are hidden, but that's for another issue...

**Pull request merged**
