### PR TITLE
Outliner - Scene View - Add Scene creation operator to header, and scene duplication operator to context menu #2792

### LINKED ISSUE #2792: Outliner - Scene View - Add Scene creation operator to header, and scene duplication operator to context menu
# Feature Request

In a full screen mode of the Outliner under Scene view, you can delete scenes, but you cannot create, make a linked copy, or make a new scene from the Scene view of the Outliner. 

**Current Scene context menu:**
image

**Added operators to the Scene Context menu that would be useful**
image

Could we add these contextual operators to the right click menu on scenes in the Scene view to make the Outliner Scene View much more usable? (not just to delete, but also create and duplicate linked, new scenes, etc)

## Reason
image

When using a full screen outliner in a second monitor, or using the scene view of the outliner for scene management to render multi-pass systems, you have to dig to add or create duplicate scenes. You're in the outliner, then you have to either go to the top right corner on the other screen to a Misc toolbar group to manage scenes OR you have to go to the Scene tab in the property editor to manage your scenes. Both in editors that are disconnected from the outliner scene management view.  

We already have the operator "Delete Scene" located in the scene management dropdown system and in the outliner, but the other operators are missing from the UX. To have the ability to not only remove scenes, but also create and manage scenes in the Scene View of the Outliner would... save a tonne of time zig zagging through different editors to manage one thing.. scenes (or Render Passes).

### PR DESCRIPTION
**Pull request by iyadahmed**
Fixes #2792
I think we might need a new icon for the new button
image

### CODE REVIEW

**Comment by ReinerBforartists** [comment]
@iyadahmed , could you please go over the comments again. Please always comment your changes. Or the next merge will kill the changes ...

**Comment by iyadahmed** [comment]
> @iyadahmed , could you please go over the comments again. Please always comment your changes. Or the next merge will kill the changes ...

Hi sure commenting now

**Comment by iyadahmed** [comment]
done ✅

**Comment by iyadahmed** [comment]
I need to add more comments will do asap

**Comment by iyadahmed** [comment]
Done

**Comment by ReinerBforartists** [comment]
Thanks :)

We can use the ADD icon for the new button. It's the same add button that is used in all other props for adding new content.

**Comment by iyadahmed** [comment]
> Thanks :)
> 
> 
> 
> We can use the ADD icon for the new button. It's the same add button that is used in all other props for adding new content.

Yep but it doesn't indicate scene, so maybe an icon similar the the new collection icon that we see in screenshot, but instead the scene icon with a little + on bottom right

**Comment by iyadahmed** [comment]
Or maybe we hide new collection button from the outliner scene view and only show it in the outliner view layer view

**Comment by iyadahmed** [comment]
Or just a new icon would be more consistent

**Comment by ReinerBforartists** [comment]
Still this confusion? I thought the issue was clear now :/

The new scene button does not belong into the right click menu. It will be in the header menu only. In the Scene panel. The collection menu has nothing to do with the issue at all.

**Comment by ReinerBforartists** [comment]
I'm in the middle of the merge at the moment. I will have a closer look at this once i am finished with it.

**Comment by iyadahmed** [comment]
> Still this confusion? I thought the issue was clear now :/
> 
> The new scene button does not belong into the right click menu. It will be in the header menu only. In the Scene panel. The collection menu has nothing to do with the issue at all.

yes no confusion about this

I mean the svg icon for it

**Comment by ReinerBforartists** [comment]
You want to change the plus sign? Plus sign is add for me.

**Comment by iyadahmed** [comment]
Ah not change, you see the icon for the new button we just added for scene doesn't have an add sign, 

We need to add an add sign to it

**Comment by ReinerBforartists** [comment]
Yeah, but we don't use the New item. Just the copy items should show in the rmb menu. So i am still confused what you want to achieve here.

**Comment by iyadahmed** [comment]
Ok nvm, waiting for pull request 😄

**Comment by ReinerBforartists** [comment]
As told, i am in the middle of the merge. Going through the commit log at the moment. Means it will still take a while. Sorry :)

But you can meanwhile also implement the panel in the header if you want. This panel doesn't exist yet from what i can see in the pull request code :)

**Comment by iyadahmed** [comment]
Ok no problem, yes the panel not needed because options are all in context menu no worries focus on merge first

**Comment by ReinerBforartists** [comment]
> Ok no problem, yes the panel not needed because options are all in context menu no worries focus on merge first

What? O_O

It's the other way around. The rmb menu entries are the bits that are not needed. It's the unnecessary double entry that i accepted as a compromise to meet you half way. The panel is the vital part that is required by design.

And to repeat my question, the create new scene does not belong into the rmb menu. Just the copy parts. So again, why is there a create new scene in the rmb menu code? We talked clearly not to do that.

Just as a reminder, i will not accept a commit where you can find the create new scene item in the rmb menu. And at the moment there is one. Please fix this code.

**Comment by iyadahmed** [comment]
There's in code but it is commented out

**Comment by iyadahmed** [comment]
> > Ok no problem, yes the panel not needed because options are all in context menu no worries focus on merge first
> 
> 
> 
> What? O_O
> 
> 
> 
> It's the other way around. The rmb menu entries are the bits that are not needed. It's the unnecessary double entry that i accepted as a compromise to meet you half way. The panel is the vital part that is required by design.
> 
> 
> 
> And to repeat my question, the create new scene does not belong into the rmb menu. Just the copy parts. So again, why is there a create new scene in the rmb menu code? We talked clearly not to do that.
> 
> 
> 
> Just as a reminder, i will not accept a commit where you can find the create new scene item in the rmb menu. And at the moment there is one. Please fix this code.

Will do the panel ok, I misunderstood

**Comment by ReinerBforartists** [comment]
Excellent. Thanks :)

I had now a look at what we have. Just to make sure, this was the proposal. And there is just the panel missing. Your code confused me ^^

Yes, with this panel it is one click more now to create a new scene. But now everything is together again, like in the scene prop. And now you can click ten times in a row to create ten new scenes. Or copy the active one. Which is much faster then than the rmb menu.

scenepanel

**Comment by ReinerBforartists** [comment]
Sorry to poke you again. But could you please with every commit add the issue number? We have again commits like 

Add more /bfa */ comments
Add autosmooth normals panel to toolbar
fix-python-notfound
UI: Freestyle UI Upgrade

etc. in the commit list of the release note now. Without a chance now to ever find out what issue it was.

**Comment by iyadahmed** [comment]
Ok much clear now, concept screenshots are important 😄

**Comment by ReinerBforartists** [comment]
I will do my best to think about more proposal shots in the future :)

**Comment by iyadahmed** [comment]
> Sorry to poke you again. But could you please with every commit add the issue number? We have again commits like 
> 
> 
> 
> Add more /bfa */ comments
> 
> Add autosmooth normals panel to toolbar
> 
> fix-python-notfound
> 
> UI: Freestyle UI Upgrade
> 
> 
> 
> etc. in the commit list of the release note now. Without a chance now to ever find out what issue it was.

Hi sure will do

**Pull request closed without merging**
