### PR TITLE
fix for 3828-preference-s-viewport-indend-playback-samples-checkbox-a…

### PR DESCRIPTION
**Pull request by Blenux**
-- removed the extra prop and moved next to show_playback_fps prop since it's to be used with it, hide if disabled.

Screenshot_20231013_173131

### CODE REVIEW

**Comment by ReinerBforartists** [comment]
Does the prop show the triangle when off?

**Comment by Blenux** [comment]
ah right I forgot, will fix

**Comment by Blenux** [comment]
Good?
https://github.com/Bforartists/Bforartists/assets/25260650/8736a623-df1e-4a38-a68d-270cd5ab1241

**Comment by ReinerBforartists** [comment]
I would as told have put the slider behind the prop. And show the triangle button just when it is off.

**Comment by Blenux** [comment]
Third time the charm :smile: 


https://github.com/Bforartists/Bforartists/assets/25260650/1ede7338-1a8c-48e2-8fad-3e708cbe6dff

**Comment by ReinerBforartists** [comment]
Yay \o/

**Comment by ReinerBforartists** [comment]
Don't forget to document :)

**Pull request merged**
