### PR TITLE
Sculpt Mode - Tool tab - Brush Settings - Align Front Faces Only prop left

### LINKED ISSUE #1890: Sculpt Mode - Tool tab - Brush Settings - Align Front Faces Only prop left
We align props at the left side.

Removed part, since we agree about the change to be a good thing:
(And we don't grey out if we don't have to. We don't show the prop then.

There are corner cases where it makes sense to show a greyed out prop. And this prop here could be one of them. So we should discuss this part.)

alignpropleft

### PR DESCRIPTION
**Pull request by iyadahmed**
Fixes #1890 
image

### CODE REVIEW

**Comment by ReinerBforartists** [comment]
Sorry. that was propably caused by my comment. In this case you could also use col.use_property_split = False. And it is in fact the better solution. With col just the current column is affected. And there is also no need to set it to True then again. This is always something to test if a property_split_false leads to unexpected side effects below the current change.

Could you please replace layout.use_property_split = False by col.use_property_split = False? And remove the layout.use_property_split = True?

**Comment by iyadahmed** [comment]
> Sorry. that was propably caused by my comment. In this case you could also use col.use_property_split = False. And it is in fact the better solution. With col just the current column is affected. And there is also no need to set it to True then again. This is always something to test if a property_split_false leads to unexpected side effects below the current change.
> 
> Could you please replace layout.use_property_split = False by col.use_property_split = False? And remove the layout.use_property_split = True?

sure will replace it now

**Comment by ReinerBforartists** [comment]
Perfect. Many thanks :)

**Comment by iyadahmed** [comment]
Done

**Pull request merged**
